- name: Run pre_update hooks
  vars:
    hooks: "{{ pre_update | default([]) }}"
    step: pre_update
  ansible.builtin.import_playbook: ./hooks.yml

- name: Update playbook
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Changing cifmw_repo_setup_promotion to target version
      ansible.builtin.set_fact:
        cifmw_repo_setup_promotion: "{{ (cifmw_repo_setup_promotion_target is defined) | ternary(cifmw_repo_setup_promotion_target, cifmw_repo_setup_promotion) }}"

    - name: Run repo_setup
      ansible.builtin.include_role:
        name: repo_setup
        tasks_from: configure.yml

    - name: Run update
      tags:
        - update
      ansible.builtin.import_role:
        name: update

    - name: Fail job
      ansible.builtin.fail:
        msg: The job failed.

- name: Run post_update hooks
  vars:
    hooks: "{{ post_update | default([]) }}"
    step: post_update
  ansible.builtin.import_playbook: ./hooks.yml
